export const allSources = [
  { id: "bbc-news", name: "BBC News" },
  { id: "cnn", name: "CNN" },
  { id: "the-verge", name: "The Verge" },
  { id: "techcrunch", name: "TechCrunch" },
  { id: "the-wall-street-journal", name: "The Wall Street Journal" },
  { id: "reuters", name: "Reuters" },
  { id: "bloomberg", name: "Bloomberg" },
  { id: "engadget", name: "Engadget" },
  { id: "nytimes", name: "New York Times" },
  { id: "guardian", name: "The Guardian" },
];

export const allCategories = [
  "Technology",
  "Artificial Intelligence",
  "Software Development",
  "Gadgets and Devices",
  "Mobile Apps",
  "Internet of Things (IoT)",
  "Cybersecurity",
  "Blockchain and Cryptocurrency",
  "Cloud Computing",
  "Data Science and Analytics",
  "Startups and Innovations",
  "Health and Wellness",
  "Fitness",
  "Nutrition",
  "Mental Health",
  "Diseases and Conditions",
  "Meditation and Mindfulness",
  "Healthcare Industry",
  "Alternative Medicine",
  "Beauty and Skincare",
  "Aging and Longevity",
  "Lifestyle",
  "Travel",
  "Fashion",
  "Food and Recipes",
  "Home and Garden",
  "Relationships",
  "Parenting",
  "Hobbies and Crafts",
  "Personal Development",
  "Sustainability and Green Living",
  "Education",
  "Online Learning",
  "Study Tips",
  "Career Guidance",
  "Educational Technology (EdTech)",
  "Skill Development",
  "Academic Research",
  "Language Learning",
  "Scholarships and Funding",
  "Business and Finance",
  "Personal Finance",
  "Investing",
  "Entrepreneurship",
  "Marketing and Advertising",
  "Real Estate",
  "E-commerce",
  "Leadership and Management",
  "Taxation and Laws",
  "Business Trends and News",
  "Entertainment",
  "Movies",
  "Music",
  "Television Shows",
  "Celebrity News",
  "Books and Literature",
  "Gaming",
  "Theater and Arts",
  "Festivals and Events",
  "Science",
  "Space Exploration",
  "Physics and Chemistry",
  "Biology and Genetics",
  "Environmental Science",
  "Scientific Discoveries",
  "Research and Experiments",
  "Technology in Science",
  "Health Sciences",
  "Sports",
  "Football (Soccer)",
  "Cricket",
  "Basketball",
  "Olympics",
  "Fitness Competitions",
  "Esports",
  "Sports Gear and Equipment",
  "Athlete Profiles",
  "Politics and Current Affairs",
  "International News",
  "Domestic News",
  "Elections",
  "Policy Analysis"
];

export const allAuthors = [
  "Matt Stevens",
  "Elisabeth Vincentelli",
  "Manuel Betancourt",
  "The New York Times",
  "Devika Girish",
  "Nicole Herrington and Rachel Sherman",
  "Robin Kawakami",
  "Dina Gachman",
  "Lisa Chen",
  "Elana Klein",
  "Mike Fazioli",
  "Robert Taylor",
  "Brittany Vincent",
  "Gizmodo Deals",
  "Bryan Cockfield",
  "Callie Ahlgrim",
  "Ryan Waniata, Gear Team",
  "Joe Tilleli",
  "Lawrence Bonk",
];
